// <auto-generated />
using System;
using ExamenFinal_Analisis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenFinal_Analisis.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("ExamenFinal_Analisis.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Guatemala"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Alta Verapaz"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Baja Verapaz"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Chimaltenango"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Chiquimula"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "El Progreso"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Escuintla"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Huehuetenango"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Izabal"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Jalapa"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Jutiapa"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Petén"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Quetzaltenango"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Quiché"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Retalhuleu"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Sacatepéquez"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "San Marcos"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Santa Rosa"
                        });
                });

            modelBuilder.Entity("ExamenFinal_Analisis.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Registrado",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "EnReparto",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Entregado",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "En Devolucion",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Devuelto",
                            Orden = 5
                        });
                });

            modelBuilder.Entity("ExamenFinal_Analisis.Models.HistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaqueteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("PaqueteId");

                    b.ToTable("HistorialEstados");
                });

            modelBuilder.Entity("ExamenFinal_Analisis.Models.Paquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoRastreo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartamentoDestinoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoActualId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntentosEntrega")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remitente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoDestinoId");

                    b.HasIndex("EstadoActualId");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("ExamenFinal_Analisis.Models.HistorialEstado", b =>
                {
                    b.HasOne("ExamenFinal_Analisis.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamenFinal_Analisis.Models.Paquete", "Paquete")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Paquete");
                });

            modelBuilder.Entity("ExamenFinal_Analisis.Models.Paquete", b =>
                {
                    b.HasOne("ExamenFinal_Analisis.Models.Departamento", "DepartamentoDestino")
                        .WithMany()
                        .HasForeignKey("DepartamentoDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamenFinal_Analisis.Models.Estado", "EstadoActual")
                        .WithMany()
                        .HasForeignKey("EstadoActualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartamentoDestino");

                    b.Navigation("EstadoActual");
                });

            modelBuilder.Entity("ExamenFinal_Analisis.Models.Paquete", b =>
                {
                    b.Navigation("HistorialEstados");
                });
#pragma warning restore 612, 618
        }
    }
}
